# Generated by Django 5.1.6 on 2025-04-03 07:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_time_time_in_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='time_in_minutes',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Value must be greater than or equal to 0'), django.core.validators.MaxValueValidator(500, message='Value must be less than or equal to 500')]),
        ),
    ]
