# Generated by Django 5.1.6 on 2025-04-17 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_time_distance_remove_time_approved_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.AlterField(
            model_name='read',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
