# Generated by Django 5.1.6 on 2025-04-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_profile_city_alter_read_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='read',
            name='date',
            field=models.DateField(),
        ),
    ]
