# Generated by Django 5.1.6 on 2025-04-17 09:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_read_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='read',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
