# Generated by Django 5.1.7 on 2025-04-22 12:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_read_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='number_of_pages',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Waarde moet groter dan of gelijk zijn aan 1!'), django.core.validators.MaxValueValidator(4032, message="Er bestaat geen boek met meer dan 4032 pagina's!")]),
        ),
        migrations.AlterField(
            model_name='read',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='read',
            name='score',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Waarde moet grooter of gelijk zijn aan 0'), django.core.validators.MaxValueValidator(10, message='Waarde moet kleiner dan of gelijk zijn aan 10')]),
        ),
    ]
